name: EC2 Deployment

on:
  workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the LAB BRANCH of your repository code
        uses: actions/checkout@v4
        with:
          ref: aws-project
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd /home/ec2-user/dice
            bash resources/deploy_ec2.sh